### ISSUE TITLE
Division of labor

### ISSUE THREAD

**Issue by steffansluis** [BEP-store/final_report#10]
Does the report allow the reader to understand how the software development 
methodology was applied? Does the report allow the reader to understand the division of labor among members of the team and how the team communicated (both among themselves and with the Coach and the Client)?
- [ ] Communication (process) @WouterKvG
- [ ] Personal & Shared effort (Process reflection, appendix) @bartist @steffansluis @WouterKvG

**Comment by WouterKvG** [comment]
Twitter, GitHub, two-weekly meetings
