### ISSUE TITLE
Big picture

### ISSUE THREAD

**Issue by steffansluis** [BEP-store/final_report#2]
Is the larger context and vision of the project described? What is the potential impact on 
day‐to‐day business or business, on people’s daily lives, on society at large?
- [ ] larger context and vision of the project 
- [ ] potential impact society

**Comment by steffansluis** [comment]
I think this is covered by the section extensibility under solution.  It doesn't mention these things directly, but it does focus on the big picture. @bartist @WouterKvG Please confirm

**Comment by bartist** [comment]
I agree, 
Both points are discussed in that section
